version: 2
updates:
  # Reusable modules
  - package-ecosystem: "terraform"
    directory: "/proxmox-vm"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/proxmox-file"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/proxmox-sdn"
    schedule:
      interval: "weekly"

  # Primary execution environment
  - package-ecosystem: "terraform"
    directory: "/envs/generic"
    schedule:
      interval: "weekly"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
