#cloud-config
timezone: "America/Denver"
packages:
  - qemu-guest-agent
runcmd:
  - apt update
  - apt upgrade -y
  - reboot now
users:
  - name: jderose
    groups: sudo
    shell: /bin/bash
    ssh-authorized-keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCUGU3paDWQDG0DdqP7iBlFPwa9Y6Uu8IuV20eiFVH0htKP9UTlKJaYh6+Ef2d/2f98Bhw+TixC/v9EFWN76Rd+ddqI5ez5lc1pkmp+jxsASQmJYt+kNQEoo7hOj01mNBb0WGsZvJqtbHCHXq5yHI5+H3DpNJ9n/9oJK/MSH5kMKkVTX5ACX2bud6dizTIRd2X5wzmmCLQyl0N/QRoMQVokfE3hP5MIqoaPRiAB6FblWAjwjh4qRTStx8kwR4If2DN/S5pSuKUE6OjCTsoMo0rvZOzGdN/lbPCSx9QaXMUw1lpboDik9NGhOL9mBJ+MY96ZQr2R86LN7q7x1jag4kQ18z5qWh5VQBA0AgYb4fHKoaw5600cW9YbkmnaxnSQjPcP0W8fm19MMTj7WurOhkOdzLd21sW7cVUscfU+nMY8ZX2P/7s1MgLmF8TldEXypX+WfbEmEm0nphtdl6W9ubzmFWmgZIRlIw+Lr0IzaWSVanLOtRpGbPZHqzUooF7Ay8= jderose@pve1"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCUIcnWQJ1PN6uaFB67HD17rKQSY4w2g2JRTD6/1LaJhXxSZe9n50yf4/hek+xlCdnGpWxRrS3PTaLFFMB150h+qt2MjwceWRfXb4MAB6RDxFwoY+Gw9VRZ/SfzTCieADVUBdUUcY2pX6GGnCE5+HM6x2NF3w0vHA5RyMt41n+XW34vmrZUPtGiHnAb4VI7LaWj1ROPmf1UVEggFiEDqm7RMG4da2QoJucND22HDugHYT3J45ZC16F6XsAYX9sYKFoFDFvE3apSztrRejz9ON0tGJSVMDZ2NvcJezpTCpBRKtKP4SJpfwWx3U3CXnGc17mvaJEHiJv+opr4RVSQXlYjDkv1VhpC60gZOsXKVmt0IMs8ZSEIDXsJQXaAXI62A6rTqW4dDPOxsQOHeG/OlYUjbNsZUvFESPSE0YhaAUM779lNsUpxaVOQIa1aiwBW6asQux4cN4aicpIlia8Em7Sg6K3kSAZwCosdIfZwyq7kmp2RDlqkgW6VM7NCWSjavgM= jderose@studio"
    sudo: ALL=(ALL) NOPASSWD:ALL

